apiVersion: v1
kind: ServiceAccount

metadata:
  name: cloudsql-proxy
  namespace: robotshop
  annotations:
    iam.gke.io/gcp-service-account: cloudsql-proxy@ps-devops-project.iam.gserviceaccount.com