apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: shipping
  newName: us-east1-docker.pkg.dev/ps-devops-project/robotshop/shipping
  newTag: "10"